### ISSUE TITLE
May I ask if the experimental effect will still be so good when  group num >2

### ISSUE THREAD

**Issue by ZeLiGuan** [illidanlab/FADE#2]
May I ask if the experimental effect will still be so good when  group num >2
By the way, how can i make group num >2?

**Comment by jyhong836** [comment]
Hi,
1. Multi-group fairness is still an open problem in the area of fairness. Our method can be extended to multi-group cases when you translate multi-group problems into paired binary-group problems. But we have not explored that yet. You may need to tune the trade-off between different groups.
2. Like I said, make multi-group problems into paired binary-group problems.

Hope my replies help.

**Comment by ZeLiGuan** [comment]
Thank you very much for your reply
